# Usamos la imagen oficial de gem5 con todas las dependencias
FROM ghcr.io/gem5/devcontainer:latest

USER root

# 1. Instalamos OpenSSH, herramientas de red y utilidades de procesos (killall)
RUN apt-get update && apt-get install -y \
    openssh-server \
    iproute2 \
    iputils-ping \
    psmisc \
    && rm -rf /var/lib/apt/lists/*

# 2. Habilitar explícitamente el login de root por SSH dentro del contenedor
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config

# Exponemos el puerto SSH estándar del contenedor (luego el Compose lo mapeará al 2222 o 2224)
EXPOSE 22

# Arrancamos el demonio SSH por defecto
CMD ["/usr/sbin/sshd", "-D"]