services:
  master:
    image: felixgnarocki/gem5-dist-node:latest
    privileged: true
    network_mode: "host"
    volumes:
      - /home/felix/ucm:/workspaces
      - /dev/kvm:/dev/kvm
    secrets:
      - source: ssh_private_key
        target: id_rsa
      - source: ssh_public_key
        target: authorized_keys
      - source: ssh_config
        target: config
    entrypoint: >
      bash -c "mkdir -p /root/.ssh /var/run/sshd &&
               ssh-keygen -A &&
               cp /run/secrets/id_rsa /root/.ssh/id_rsa &&
               cp /run/secrets/authorized_keys /root/.ssh/authorized_keys &&
               cp /run/secrets/config /root/.ssh/config &&
               chmod 700 /root/.ssh &&
               chmod 600 /root/.ssh/id_rsa &&
               chmod 644 /root/.ssh/authorized_keys /root/.ssh/config &&
               /usr/sbin/sshd -D -p 2222"

secrets:
  ssh_private_key:
    file: ./ssh_keys/id_rsa
  ssh_public_key:
    file: ./ssh_keys/id_rsa.pub
  ssh_config:
    file: ./ssh_keys/config