---
version: '3.8'

services:
    master:
        image: felixgnarocki/gem5-dist-node:latest
        privileged: true
        networks:
            - gem5_network
        deploy:
            placement:
                constraints:
                    - node.role == manager
        secrets:
            - source: ssh_private_key
              target: /root/.ssh/id_rsa
              mode: 0600
            - source: ssh_public_key
              target: /root/.ssh/authorized_keys
              mode: 0600
        volumes:
            - /home/felix/ucm:/workspaces # Monta tu código de gem5
            - type: bind
              source: /dev/kvm
              target: /dev/kvm
    # Mantiene el master vivo para que tú entres a ejecutar los comandos
        command: /usr/sbin/sshd -D
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN

    worker1:
        image: felixgnarocki/gem5-dist-node:latest
        privileged: true
        networks:
            - gem5_network
        secrets:
            - source: ssh_public_key
              target: /root/.ssh/authorized_keys
              mode: 0600
        volumes:
            - /home/felix/ucm:/workspaces # Todos los nodos deben ver los mismos archivos
            - type: bind
              source: /dev/kvm
              target: /dev/kvm
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN

    worker2:
        image: felixgnarocki/gem5-dist-node:latest
        privileged: true
        networks:
            - gem5_network
        secrets:
            - source: ssh_public_key
              target: /root/.ssh/authorized_keys
              mode: 0600
        volumes:
            - /home/felix/ucm:/workspaces # Todos los nodos deben ver los mismos archivos
            - type: bind
              source: /dev/kvm
              target: /dev/kvm
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN

    worker3:
        image: felixgnarocki/gem5-dist-node:latest
        privileged: true
        networks:
            - gem5_network
        secrets:
            - source: ssh_public_key
              target: /root/.ssh/authorized_keys
              mode: 0600
        volumes:
            - /home/felix/ucm:/workspaces # Todos los nodos deben ver los mismos archivos
            - type: bind
              source: /dev/kvm
              target: /dev/kvm
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN

    worker4:
        image: felixgnarocki/gem5-dist-node:latest
        privileged: true
        networks:
            - gem5_network
        secrets:
            - source: ssh_public_key
              target: /root/.ssh/authorized_keys
              mode: 0600
        volumes:
            - /home/felix/ucm:/workspaces # Todos los nodos deben ver los mismos archivos
            - type: bind
              source: /dev/kvm
              target: /dev/kvm
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN

networks:
    gem5_network:
        driver: overlay
        attachable: true

secrets:
    ssh_private_key:
        file: ./ssh_keys/id_rsa
    ssh_public_key:
        file: ./ssh_keys/id_rsa.pub
